title: "Forgiven and Free"
description: "A Lutheran Method for Escaping the Pornography Trap"
baseurl: ""
url: "https://forgivenandFree.github.io"

defaults:
  - scope:
      path: "chapters"
    values:
      layout: default
  - scope:
      path: ""
    values:
      layout: default
