title: "Free Indeed"
description: "A Lutheran Method for Escaping the Pornography Trap"
baseurl: "/free_indeed"
url: "https://forgivenandFree.github.io"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: "chapters"
    values:
      layout: default
  - scope:
      path: ""
    values:
      layout: default
